name: Flutter CI

# This worklow will run on every commit on main branch
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Setting up the Java Environment to build the android app
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Settting up flutter environment
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: 'Getting flutter packages'
      run: flutter pub get
        
    # Check for any formatting issues in the code. Returns 1 if any changes made.
    # - run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .

    - name: 'Running tests'
      run: flutter test

    - name: 'Building apk'
      run: flutter build apk
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
